"""rename book to ebook

Revision ID: 0019923df1c9
Revises: 751b8d4727ca
Create Date: 2017-05-12 13:12:53.159749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0019923df1c9'
down_revision = '751b8d4727ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('author', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=128), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=128), nullable=True),
    sa.Column('author', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=32), nullable=True),
    sa.Column('description', mysql.TEXT(collation=u'utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('downloads', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('file_path', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=128), nullable=True),
    sa.Column('uploader_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], [u'categories.id'], name=u'books_ibfk_1'),
    sa.ForeignKeyConstraint(['uploader_id'], [u'users.id'], name=u'books_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8mb4_unicode_ci',
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('ebooks')
    # ### end Alembic commands ###
