"""add ebook type and size

Revision ID: 0ab9e60867a5
Revises: ed3b83ef0feb
Create Date: 2017-05-13 08:43:19.702078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab9e60867a5'
down_revision = 'ed3b83ef0feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ebooks', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('ebooks', sa.Column('file_type', sa.String(length=16), nullable=True))
    op.add_column('ebooks', sa.Column('image_path', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ebooks', 'image_path')
    op.drop_column('ebooks', 'file_type')
    op.drop_column('ebooks', 'file_size')
    # ### end Alembic commands ###
