"""add hash of email

Revision ID: 239cf1835658
Revises: 433d43f28f01
Create Date: 2017-05-12 10:49:47.154157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239cf1835658'
down_revision = '433d43f28f01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
