"""add book isbn publisher etc

Revision ID: 3ff1e3030361
Revises: d4050be603ad
Create Date: 2017-05-16 16:54:46.970003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff1e3030361'
down_revision = 'd4050be603ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_number', sa.String(length=50), nullable=True))
    op.add_column('books', sa.Column('isbn', sa.String(length=32), nullable=True))
    op.add_column('books', sa.Column('publisher', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'publisher')
    op.drop_column('books', 'isbn')
    op.drop_column('books', 'book_number')
    # ### end Alembic commands ###
