"""change user model

Revision ID: 433d43f28f01
Revises: ca0f8c7a92c8
Create Date: 2017-05-11 14:28:40.687545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '433d43f28f01'
down_revision = 'ca0f8c7a92c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'users_ibfk_1', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(u'users_ibfk_1', 'users', 'roles', ['role'], ['id'])
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'name')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
