"""add ebooks_download tables

Revision ID: 6fb37bbda661
Revises: f74bfed7ecdb
Create Date: 2017-05-26 09:52:39.877076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fb37bbda661'
down_revision = 'f74bfed7ecdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebooks_download',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ebooks_id', sa.Integer(), nullable=True),
    sa.Column('download_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ebooks_id'], ['ebooks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8mb4_unicode_ci',
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('ebooks_download')
    # ### end Alembic commands ###
