"""change table col name

Revision ID: 90715c2e01e3
Revises: 20a6643dec76
Create Date: 2017-05-27 11:02:16.882333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90715c2e01e3'
down_revision = '20a6643dec76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config_table', sa.Column('type_name', sa.String(length=100), nullable=True))
    op.drop_column('config_table', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config_table', sa.Column('type', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=100), nullable=True))
    op.drop_column('config_table', 'type_name')
    # ### end Alembic commands ###
