"""add book number colums

Revision ID: d4050be603ad
Revises: e5c3a4f4f9ca
Create Date: 2017-05-16 16:47:03.257570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4050be603ad'
down_revision = 'e5c3a4f4f9ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('rent_count', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('total_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'total_count')
    op.drop_column('books', 'rent_count')
    # ### end Alembic commands ###
